// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PalamigStore.DataAccess.Data;

#nullable disable

namespace PalamigStore.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240925234354_addForeignKeyForCategoryAndProductRelation")]
    partial class addForeignKeyForCategoryAndProductRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PalamigStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ice Candy",
                            Quantity = 45
                        },
                        new
                        {
                            Id = 2,
                            Name = "Popsicle",
                            Quantity = 20
                        },
                        new
                        {
                            Id = 3,
                            Name = "Granita",
                            Quantity = 32
                        });
                });

            modelBuilder.Entity("PalamigStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandName = "Magnolia",
                            CategoryId = 7,
                            Description = "Vanilla ice cream is a classic flavor commonly made with vanilla extract, cream, milk, and sugar.",
                            ListPrice = 200.0,
                            Price = 230.0,
                            Price100 = 20000.0,
                            Price50 = 11500.0,
                            ProductName = "Vanilla Ice Cream"
                        },
                        new
                        {
                            Id = 2,
                            BrandName = "Nestle",
                            CategoryId = 8,
                            Description = "A delightful frozen treat bursting with refreshing orange flavor, perfect for satisfying sweet cravings on hot summer days.",
                            ListPrice = 150.0,
                            Price = 125.0,
                            Price100 = 125000.0,
                            Price50 = 6250.0,
                            ProductName = "Orange Popsicle"
                        },
                        new
                        {
                            Id = 3,
                            BrandName = "Baskin-Robbins",
                            CategoryId = 9,
                            Description = "A zesty and refreshing Italian-style dessert made from freshly squeezed lemons, creating a tangy yet cooling sensation that tantalizes the taste buds with every spoonful.",
                            ListPrice = 60.0,
                            Price = 45.0,
                            Price100 = 45000.0,
                            Price50 = 2250.0,
                            ProductName = "Lemon Granita"
                        },
                        new
                        {
                            Id = 4,
                            BrandName = "Magnolia",
                            CategoryId = 10,
                            Description = "Indulge in creamy decadence with our Chocolate Ice Cream, a rich and velvety delight crafted from the finest cocoa, offering a blissful symphony of intense chocolate flavors in every scoop.",
                            ListPrice = 200.0,
                            Price = 230.0,
                            Price100 = 20000.0,
                            Price50 = 11500.0,
                            ProductName = "Chocolate Ice Cream"
                        },
                        new
                        {
                            Id = 5,
                            BrandName = "Nestle",
                            CategoryId = 7,
                            Description = "Savor the sweetness of summer with our Grape Popsicle, a burst of fruity goodness that captures the essence of ripe grapes, delivering a refreshing and satisfying treat on a stick.",
                            ListPrice = 150.0,
                            Price = 125.0,
                            Price100 = 125000.0,
                            Price50 = 6250.0,
                            ProductName = "Grape Popsicle"
                        },
                        new
                        {
                            Id = 6,
                            BrandName = "Baskin-Robbins",
                            CategoryId = 14,
                            Description = "Treat yourself to a taste of Italy with our Coffee Granita, a sophisticated dessert blending robust espresso with a hint of sweetness, offering a revitalizing and indulgent pick-me-up in every icy spoonful.",
                            ListPrice = 60.0,
                            Price = 45.0,
                            Price100 = 45000.0,
                            Price50 = 2250.0,
                            ProductName = "Coffee Granita"
                        });
                });

            modelBuilder.Entity("PalamigStore.Models.Product", b =>
                {
                    b.HasOne("PalamigStore.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
